# Generated by Django 6.0.2 on 2026-02-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akul', '0002_book_thumbnail_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulation',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='circulation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
