# Generated by Django 6.0.2 on 2026-02-09 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akul', '0003_circulation_fine_amount_circulation_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akul.book'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='days_overdue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penalty',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
