# Generated by Django 6.0.2 on 2026-03-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akul', '0008_book_qr_code_alter_student_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='qr_code',
        ),
    ]
