# Generated by Django 6.0.2 on 2026-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
