# Generated by Django 6.0.2 on 2026-02-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akul', '0004_penalty_book_penalty_days_overdue_penalty_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(default='Central City Library', max_length=200)),
                ('address', models.CharField(default='123 Main Street, City', max_length=500)),
                ('contact', models.CharField(default='+1 234 567 8900', max_length=50)),
                ('penalty_per_day', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('max_penalty', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('loan_duration', models.IntegerField(default=14)),
                ('max_books', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
