# Generated by Django 6.0.2 on 2026-03-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akul', '0005_librarysettings_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='bookrequest',
            old_name='member',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='circulation',
            old_name='member',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='penalty',
            old_name='member',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='circulation',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='student',
            table='Students',
        ),
    ]
