# Generated by Django 6.0.2 on 2026-03-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akul', '0006_rename_member_student_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='akul_student',
        ),
    ]
