# Generated by Django 6.0.2 on 2026-03-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akul', '0007_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
