# Generated by Django 6.0.2 on 2026-03-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akul', '0011_emaillog_librarysettings_enable_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., Aisle 4, Shelf B', max_length=255, null=True),
        ),
    ]
